new linkedin api endpoints.
HootsuiteLabs/python-linkedin-v2 pull request #4
Opened 2018-09-22 15:34 UTC by qasimgulzar

I have added few new linkedin api end points.

comments
JOBS
network
shares 
Search Companies
search people
Search Job

2018-09-22 16:58 UTC, reicolina commented on linkedin_v2/linkedin.py
> +    def get_groupss(self, group_id, params=None, headers=None):
What's the difference between `get_groupss` and `get_groups`? At first, I thought it was a typo 😉but they seem to behave differently, in which case, would it be possible to rename this method so is more self-explanatory?

2018-09-22 17:05 UTC, reicolina requested changes
Thanks a lot for your contribution! 🤘 I added I a couple of comments and a question for you to review. Also, do you think it would be possible to add documentation on how each of the added endpoints/methods works? You could put them in the `README`.

2018-09-22 17:05 UTC, reicolina commented on linkedin_v2/linkedin.py
> +    def get_groupss(self, group_id, params=None, headers=None):
What's the difference between get_groupss and get_groups? At first, I thought it was a typo 😉but they seem to behave differently, in which case, would it be possible to rename this method so is more self-explanatory?

2018-09-22 17:05 UTC, reicolina commented on linkedin_v2/linkedin.py
> +        #     }
If this commented-out block is not needed anymore, I would suggest to remove it.

2018-09-22 17:05 UTC, reicolina commented on linkedin_v2/linkedin.py
> +        return response.json()
Can you add a new line to the end of the file? See: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2018-09-23 13:08 UTC, reicolina requested changes
Thanks for adding the suggested modifications 👍One more thing, do you think it would be possible to add documentation for each of the added endpoints/methods? You could put them in the `README`. You can use the existing `profile` and connections` descriptions or even the original repo (https://github.com/ozgur/python-linkedin) as a reference point.

This way other developers would be aware of the existence of these endpoints within the library.

Let me know if there are questions or concerns about this suggestion.

2018-10-15 04:41 UTC, reicolina requested changes
The version should now be `0.9.6`. Also, would you mind updating the `README.md` file to reflect the new methods you added. Let me know if you need any help with that.

Thanks again for the work you've done on this PR! 🙌

2018-10-15 04:41 UTC, reicolina commented on linkedin_v2/__init__.py
> +__version__ = '0.9.3'
This should now be `0.9.6`

2019-01-14 18:23 UTC, luiscastillocr commented
do you guys need help to get this out? I would like to help!

I am currently using https://github.com/ozgur/python-linkedin but it seems to be a dead project now

2019-01-15 08:02 UTC, reicolina commented
> do you guys need help to get this out? I would like to help!
> 
> I am currently using https://github.com/ozgur/python-linkedin but it seems to be a dead project now

@luiscastillocr, yes absolutely! If you could add the documentation requested to @qasimgulzar in one of my previous comments, that would be great, and will allow us to move forward and merge this PR.

Thanks for you interest and for putting your head up! ✋

2019-01-15 17:04 UTC, luiscastillocr commented
@reicolina do you want me to create a separated PR to add the documentation? I have no write permissions to @qasimgulzar repo! :/

2019-01-15 18:08 UTC, reicolina commented
Good point @luiscastillocr. Yes, please go ahead and create a separate PR and post the link to it here so we know that they have to be merged together.

2019-01-30 01:22 UTC, andronat commented
Hello, any news regarding this? I would love to have it merged 😃

2019-02-16 03:35 UTC, reicolina commented
Hi @andronat, I’m not an admin anymore so I cannot merge this PR. Perhaps @william-beange-hs can help.

2019-02-18 15:24 UTC, luiscastillocr commented
oh I am sorry guys, we had to go through the new Linkedin Developer program registration and I am still waiting for approval, I can help with whatever you need to get this merge out as soon as I can put my hands in the V2 api

2019-06-27 07:06 UTC, s2t2 commented
> oh I am sorry guys, we had to go through the new Linkedin Developer program registration and I am still waiting for approval, I can help with whatever you need to get this merge out as soon as I can put my hands in the V2 api

@luiscastillocr how does one go about applying? I've created an app to get my profile info using this package, but I'd like to also request [recommended jobs](https://developer.linkedin.com/docs/guide/v2/jobs/recommended-jobs) using the permission "r_JYMBII", but kind of confused as to how to get access.

Thanks! Also hoping you get approved so this PR can be more fully reviewed and merged 😸

2019-06-27 15:47 UTC, luiscastillocr commented
@s2t2 the submission is still in the review process, I bet there are a lot more people in the same situation because they ended up sending us an email before the deadline to let us know they are extending the V1 access in the meantime they complete the submission review

I quote:
> As we approach the previously stated May 1, 2019 migration deadline, if you are currently using our v1.0 APIs, we will extend your v1.0 access until we’ve reviewed your submission and communicated a decision. This means we will continue to support your integration, as we work through the remaining submissions.

I will let you know guys any news

NOTE: if there is anyone can share an account with access to the V2 API, I could use it and help you to get this PR out!

2019-06-27 17:30 UTC, william-beange-hs commented
Apologies for being absent. Happy to move this along if you'd like to get it in.

2020-04-21 15:58 UTC, adriangb commented
Any updates on this? It would be great to get this merged.

2020-04-21 19:30 UTC, luiscastillocr commented
I finally got my account reviewed but I think the PR will need a little more work to get it stable and good to merge, some few things have changed in the LinkedIn API side since this PR was created that was not been considered(endpoint names, changes in the permissions, etc)

But I will be more than happy to get it working!

Any suggestions on how we can proceed? @qasimgulzar

2020-09-01 17:29 UTC, luiscastillocr commented
if anyone is interested, I've implemented the programmatic refresh tokens along with some few fixes, it is waiting in a [PR](https://github.com/qasimgulzar/python-linkedin-v2/pull/1) in the @qasimgulzar repository if he is not interested in contributing to this project anymore, I can just cancel that PR and point it directly to this repo!

thoughts? @reicolina

2023-06-14 14:41 UTC, luiscastillocr commented
BUMP! @reicolina

2026-03-27 05:07 UTC, merged